### ISSUE TITLE
README details

### ISSUE THREAD

**Issue by almereyda** [passbolt/go-passbolt-cli#14]
**Describe the bug:**

The Go ecosystem moves forward, and has new installation patterns. When running the installation command from the README, an error is thrown.

**To Reproduce:**

1. Run `go install github.com/passbolt/go-passbolt-cli`
2. See
    ```
    go install: version is required when current directory is not in a module
        Try 'go install github.com/passbolt/go-passbolt-cli@latest' to install the latest version
    ```

**Additional context**

- `go install github.com/passbolt/go-passbolt-cli@latest` works as expected, since the last tagged release was already long time ago.

**Comment by speatzle** [comment]
Does @latest also work on go 1.17 ?

**Comment by almereyda** [comment]
For me it does, yes.

```shell
$ go version
go version go1.17 linux/amd64
$ which go-passbolt-cli
~/go/bin/go-passbolt-cli
```

**Comment by speatzle** [comment]
fixed
