### ISSUE TITLE
Get specific field

### ISSUE THREAD

**Issue by almereyda** [passbolt/go-passbolt-cli#15]
**Describe the bug:**

When trying to access a secret encrypted in a multi-line description field, it is only printed in a single line together with the other fields.

**To Reproduce:**

1. Run `go-passbolt-cli get resource --id <uuid>`
2. Find the multi-line field concatenated into a single line string

**go-passbolt-cli Version:**
 - OS: linux
 - Version v0.1.7

**Additional context**

This is probably solved by #7.

**Comment by speatzle** [comment]
A issue came up during the security audit where a attacker with a malicous multiline secret/note could make the go-passbolt-cli output confuseing for users and bash parsing

I believe the fix that was implemented was to force such output to be single line.

As such this is expected behaviour.
