### ISSUE TITLE
Feature: CLI option to get the last modified date

### ISSUE THREAD

**Issue by Cisien** [passbolt/go-passbolt-cli#17]
I am using the passbolt cli to automate backups of my self-hosted instance to keepass files for offline access and disaster recovery. At this point in time, I'm not able to get the last modified date for either individual resources or the database as a whole.

This information would be helpful in preventing unnecessary duplication of data in backups.

What would be helpful is to either expose the last modification date in the resource list command, or add a new command to summarize this for me, and expose the most recent date.

**Comment by speatzle** [comment]
Currently all list Operations support a -c / --columns flag to configure which columns should be returned, for resources that flag the currently fupported values are ID, FolderParentID, Name, Username, URI, Password and Description.

It Should be Pretty Easy for me to Add Creating Time and Update Time Columns to this list. Would that work for you?

**Comment by speatzle** [comment]
As a Side note go-passbolt-cli has a experimental feature to export passbolt to keepass files which might interest you:
https://github.com/passbolt/go-passbolt-cli/wiki/passbolt_export_keepass

Any feedback / suggestions would be appreciated.

**Comment by Cisien** [comment]
That would be perfect, and I'm actually using this keepass export feature to handle what I described above. It's working great!

**Comment by speatzle** [comment]
Cool.

The Columns CreatedTimestamp and ModifiedTimestamp have been merged.

You can use them by using -c in a list command like this:
 `passbolt list resources -c ID -c Name -c CreatedTimestamp -c ModifiedTimestamp`

Additionally i also Just merged JSON Output Support which should make Scripting easier. The JSON Output includes the Timestamp fields by default.

Released in v0.2.0
