### ISSUE TITLE
Add Keepass Export

### ISSUE THREAD

**Issue by speatzle** [passbolt/go-passbolt-cli#5]
Add a sub-command to export Passwords to a Keepass file.

This is useful for automatic Passbolt backups of a selfhosted instance which might go offline but may contain passwords needed to fix the instance.

Potential Library: https://github.com/tobischo/gokeepasslib

**Comment by Cisien** [comment]
The current experimental implementation works well. Below is a short shell script to perform a backup and persist it as an Azure KeyVault secret if any of the secrets have been modified in the past day.

```bash
#!/bin/bash

if (( $(date -d "yesterday" +%s) < $(date -d $( passbolt list resource -c ModifiedTimestamp | sort | tail -2 | head -1) +%s ) ))
then
    echo "The last modified date is within the past day, running backup"
    az login --service-principal -u $APP_ID \
        -p ~/.azure/auth-cert.pem --tenant $TENANT --allow-no-subscriptions \
        -o none --only-show-errors

    rm ~/.passbolt/keepass-backup.kdbx 2&> /dev/null
    passbolt export keepass --file ~/.passbolt/keepass-backup.kdbx --password $PASS

    az keyvault secret set --vault $VAI:T \
        --name $SECRET_NAME --encoding base64 \
        --file ~/.passbolt/keepass-backup.kdbx \
        -o none --only-show-errors
    rm ~/.passbolt/keepass-backup.kdbx 2&> /dev/null
fi
```

**Comment by speatzle** [comment]
The current Implementation Works Well enough and has had TOTP Support and Better Error Handling/Skipping Added in #43.

Closing
