### ISSUE TITLE
[feature request] Package for nix

### ISSUE THREAD

**Issue by pbek** [passbolt/go-passbolt-cli#51]
It would be great to have a package for Nix.

So I created one, if anyone wants to test:
https://github.com/NixOS/nixpkgs/pull/304480

**Comment by speatzle** [comment]
Hi, thanks for packaging!

From Looking at the Package File, i can see that you set the LD Flag for version but not for commit or date. It will work this way but will show unknown for both of those in the version flag's output, you can set them like goreleaser (https://goreleaser.com/cookbooks/using-main.version).

Also go-passbolt-cli has man pages which i don't see included, you can generate the man pages using `mkdir man && passbolt gendoc --type man` and then move them to the correct place.

Ill see about setting up a NixOS Install SoonTM to actually test the package.

**Comment by speatzle** [comment]
Also since this is a Community Project, i don't know if we want to set the homepage to `https://www.passbolt.com`. Id rather set it to this GitHub Repo.

**Comment by pbek** [comment]
Thank you for the feedback!

> From Looking at the Package File, i can see that you set the LD Flag for version but not for commit or date. It will work this way but will show unknown for both of those in the version flag's output, you can set them like goreleaser (https://goreleaser.com/cookbooks/using-main.version).

I didn't see a clear way what to be set in nixpkgs, most go packages just don't use these flags or fake some. I can fake some information too...

> Also since this is a Community Project, i don't know if we want to set the homepage to https://www.passbolt.com. Id rather set it to this GitHub Repo.

Of course!

**Comment by pbek** [comment]
I did changes to https://github.com/NixOS/nixpkgs/pull/304480/files.
Happy nix-install. 😊

**Comment by pbek** [comment]
Add showed the output for man-pages and the shell-completion here:

https://github.com/NixOS/nixpkgs/pull/304480#issuecomment-2058912964

**Comment by pbek** [comment]
Package was merged, see https://search.nixos.org/packages?channel=unstable&show=go-passbolt-cli&from=0&size=50&sort=relevance&type=packages&query=passbolt.
